# Generated by Django 3.1.4 on 2021-04-26 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JadwalModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateTimeField()),
                ('title', models.CharField(max_length=100)),
                ('penceramah', models.CharField(max_length=100)),
                ('online', models.BooleanField()),
            ],
        ),
    ]
