# Generated by Django 3.1.4 on 2021-05-11 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appmasjid', '0002_jadwalmodel_selesai'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfaqModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('jumlah', models.IntegerField()),
                ('nama', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JenisZakatModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PenceramahModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penceramah', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ZakatModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('nama', models.CharField(max_length=100)),
                ('total', models.IntegerField()),
                ('jenis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appmasjid.jeniszakatmodel')),
            ],
        ),
        migrations.AlterField(
            model_name='jadwalmodel',
            name='penceramah',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appmasjid.penceramahmodel'),
        ),
    ]
