# Generated by Django 3.1.4 on 2021-05-12 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appmasjid', '0003_auto_20210511_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonasiModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('jumlah', models.IntegerField()),
                ('nama', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JenisShodaqoh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ShodaqohModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('nama', models.CharField(max_length=100)),
                ('total', models.IntegerField()),
                ('jenis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appmasjid.jeniszakatmodel')),
            ],
        ),
    ]
