# Generated by Django 3.1.4 on 2021-05-12 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmasjid', '0005_auto_20210512_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zakatmodel',
            name='tanggal',
            field=models.DateField(),
        ),
    ]
