# Generated by Django 3.1.4 on 2021-05-20 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmasjid', '0009_auto_20210520_0648'),
    ]

    operations = [
        migrations.CreateModel(
            name='WakafModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('jumlah', models.IntegerField()),
                ('nama', models.CharField(max_length=100)),
            ],
        ),
    ]
