# Generated by Django 3.1.4 on 2021-05-20 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmasjid', '0010_wakafmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='jadwalmodel',
            name='link',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
