# Generated by Django 3.1.4 on 2021-05-20 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmasjid', '0012_kegiatanmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kegiatanmodel',
            name='thumbnail',
            field=models.ImageField(upload_to='thumbnail/% Y/% m/% d/'),
        ),
    ]
