# Generated by Django 3.1.4 on 2021-05-20 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmasjid', '0014_auto_20210520_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='kegiatanmodel',
            name='upload',
            field=models.DateField(auto_now=True),
        ),
    ]
