# Generated by Django 3.1.4 on 2021-05-21 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmasjid', '0016_auto_20210521_0700'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayananModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=20)),
                ('no_telp', models.CharField(max_length=12)),
            ],
        ),
        migrations.AlterField(
            model_name='zakatmodel',
            name='jenis',
            field=models.CharField(choices=[('Maal', 'Maal'), ('Fitrah', 'Fitrah')], max_length=10),
        ),
    ]
