# Generated by Django 3.1.4 on 2021-05-21 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appmasjid', '0017_auto_20210521_0735'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JenisZakatModel',
        ),
    ]
