# Generated by Django 3.1.4 on 2021-10-06 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmasjid', '0020_jadwaljumatmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shodaqohmodel',
            name='jenis',
        ),
        migrations.RemoveField(
            model_name='zakatmodel',
            name='jenis',
        ),
        migrations.AddField(
            model_name='donasimodel',
            name='link',
            field=models.CharField(default='https://www.google.com', max_length=50),
        ),
        migrations.AddField(
            model_name='infaqmodel',
            name='link',
            field=models.CharField(default='https://www.google.com', max_length=50),
        ),
        migrations.AddField(
            model_name='layananmodel',
            name='link',
            field=models.CharField(default='https://www.google.com', max_length=100),
        ),
        migrations.AddField(
            model_name='layananmodel',
            name='nama_pengurus',
            field=models.CharField(default='Nama', max_length=50),
        ),
        migrations.AddField(
            model_name='shodaqohmodel',
            name='link',
            field=models.CharField(default='https://www.google.com', max_length=50),
        ),
        migrations.AddField(
            model_name='wakafmodel',
            name='link',
            field=models.CharField(default='https://www.google.com', max_length=50),
        ),
        migrations.AddField(
            model_name='zakatmodel',
            name='link',
            field=models.CharField(default='https://www.google.com', max_length=50),
        ),
        migrations.DeleteModel(
            name='JenisShodaqoh',
        ),
    ]
