# Generated by Django 3.1.4 on 2021-10-07 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmasjid', '0021_auto_20211007_0138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layananmodel',
            name='link',
        ),
        migrations.AddField(
            model_name='layananmodel',
            name='thumbnail',
            field=models.ImageField(default='', upload_to='static/thumbnail_layanan/'),
        ),
    ]
