# Generated by Django 3.1.4 on 2021-10-31 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmasjid', '0023_auto_20211020_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donasimodel',
            name='link',
            field=models.CharField(default='https://www.google.com', max_length=200),
        ),
        migrations.AlterField(
            model_name='imammodel',
            name='foto',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='infaqmodel',
            name='link',
            field=models.CharField(default='https://www.google.com', max_length=200),
        ),
        migrations.AlterField(
            model_name='kegiatanmodel',
            name='thumbnail',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='layananmodel',
            name='thumbnail',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='shodaqohmodel',
            name='link',
            field=models.CharField(default='https://www.google.com', max_length=200),
        ),
        migrations.AlterField(
            model_name='wakafmodel',
            name='link',
            field=models.CharField(default='https://www.google.com', max_length=200),
        ),
        migrations.AlterField(
            model_name='zakatmodel',
            name='link',
            field=models.CharField(default='https://www.google.com', max_length=200),
        ),
    ]
