# Generated by Django 3.1.4 on 2021-10-31 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmasjid', '0024_auto_20211031_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='jadwaljumatmodel',
            name='tema',
            field=models.CharField(default='-', max_length=100),
        ),
    ]
