# Generated by Django 3.1.4 on 2021-11-15 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmasjid', '0025_jadwaljumatmodel_tema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layananmodel',
            name='nama',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='layananmodel',
            name='nama_pengurus',
            field=models.CharField(default='Nama', max_length=100),
        ),
    ]
